version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: discord-mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "discord-db"
      MYSQL_USER: "shirin"
      MYSQL_PASSWORD: "1234"
    ports:
      - "3306:3306"
    volumes:
      - discord-mysql-data:/var/lib/mysql

volumes:
  discord-mysql-data:
